#!/usr/bin/env python3
"""Generate src/blowfish_init.h: Blowfish's initial P-array and S-boxes,
which are the hexadecimal digits of the fractional part of pi.

    python3 scripts/gen-blowfish.py > src/blowfish_init.h

Needs mpmath (only for regenerating the header)."""
from mpmath import mp, pi, floor, mpf

words = 18 + 4 * 256
mp.prec = 32 * words + 64
frac = pi - 3
bits = int(floor(frac * mpf(2) ** (32 * words)))
w = [(bits >> (32 * (words - 1 - i))) & 0xffffffff for i in range(words)]
assert w[0] == 0x243F6A88 and w[17] == 0x8979FB1B
print("/* Generated by scripts/gen-blowfish.py - do not edit. */")
print("static const uint32_t bf_init_p[18] = {")
for i in range(0, 18, 6):
    print("\t" + " ".join(f"0x{x:08x}," for x in w[i:i + 6]))
print("};")
print("static const uint32_t bf_init_s[4][256] = {")
for b in range(4):
    print("\t{")
    s = w[18 + 256 * b: 18 + 256 * (b + 1)]
    for i in range(0, 256, 6):
        print("\t\t" + " ".join(f"0x{x:08x}," for x in s[i:i + 6]))
    print("\t},")
print("};")
