#!/usr/bin/env python3
"""Generate src/math/tables.h: lookup tables and polynomial coefficients
for the double-precision math functions, computed with mpmath at 256 bits.

    python3 scripts/gen-math.py > src/math/tables.h

Needs mpmath (pip install mpmath); only for regenerating the header."""
import struct
from mpmath import mp, mpf, exp, log, log1p, expm1, pi, sin, cos, tan, atan, asin, sqrt, floor, ldexp, sinh, tanh, asinh

mp.prec = 160

def d(x):
    """Round an mpf to the nearest double."""
    return float(mp.mpf(x))

def hexd(x):
    return float(x).hex()

def split(x, bits):
    """x as hi (with at most `bits` significant bits) + lo."""
    x = mpf(x)
    if x == 0:
        return 0.0, 0.0
    e = int(mp.floor(mp.log(abs(x), 2)))
    q = mpf(2) ** (e - bits + 1)
    hi = mp.nint(x / q) * q
    return float(hi), d(x - hi)

def dd(x):
    hi = d(x)
    return hi, d(mpf(x) - hi)

def peval(c, x):
    r = mpf(0)
    for v in reversed(c):
        r = r * x + v
    return r

def remez(f, a, b, deg, iters=30):
    """Minimax polynomial (absolute error) by the Remez exchange."""
    a, b = mpf(a), mpf(b)
    n = deg + 2
    # initial reference: Chebyshev extrema
    snap = lambda x: mpf(0) if abs(x) < mpf(2) ** -60 else x
    ref = [snap((a + b) / 2 - (b - a) / 2 * mp.cos(pi * k / (n - 1))) for k in range(n)]
    c = None
    for _ in range(iters):
        A = mp.matrix(n, n)
        y = mp.matrix(n, 1)
        for i, x in enumerate(ref):
            for j in range(deg + 1):
                A[i, j] = x ** j
            A[i, deg + 1] = (-1) ** i
            y[i] = f(x)
        sol = mp.lu_solve(A, y)
        c = [sol[j] for j in range(deg + 1)]
        err = lambda x: f(x) - peval(c, x)
        # locate the extrema of the error between sign changes
        grid = [snap(a + (b - a) * k / 2000) for k in range(2001)]
        vals = [err(x) for x in grid]
        ext = []
        start = 0
        for k in range(1, len(grid) + 1):
            if k == len(grid) or (vals[k] > 0) != (vals[start] > 0):
                seg = range(start, k)
                m = max(seg, key=lambda t: abs(vals[t]))
                ext.append(grid[m])
                start = k
        if len(ext) < n:
            break
        # keep n alternating extrema with the largest errors
        while len(ext) > n:
            if abs(err(ext[0])) < abs(err(ext[-1])):
                ext.pop(0)
            else:
                ext.pop()
        ref = ext
    grid = [snap(a + (b - a) * k / 20000) for k in range(20001)]
    maxerr = max(abs(f(x) - peval(c, x)) for x in grid)
    return c, maxerr

def poly(f, a, b, deg, name):
    """Minimax fit; coefficients lowest degree first."""
    c, err = remez(f, a, b, deg)
    print(f"/* {name}: degree {deg} on [{float(a):.6g}, {float(b):.6g}], max abs error {float(err):.3g} */")
    return [d(v) for v in c]

def emit_array(name, vals, per=2):
    print(f"static const double {name}[{len(vals)}] = {{")
    for i in range(0, len(vals), per):
        print("\t" + " ".join(f"{hexd(v)}," for v in vals[i:i + per]))
    print("};")

def emit_consts(prefix, vals):
    for i, v in enumerate(vals):
        print(f"#define {prefix}{i} {hexd(v)}")

print("/* Generated by scripts/gen-math.py - do not edit. */")

# ---- exp / exp2 / expm1: 2^(j/N) table ----
N = 128
tab = []
for j in range(N):
    hi, lo = dd(mpf(2) ** (mpf(j) / N))
    tab += [hi, lo]
print(f"#define EXP_N {N}")
emit_array("exp_tab", tab)
ln2hi, ln2lo = split(log(2) / N, 35)
print(f"#define EXP_LN2HI_N {hexd(ln2hi)}")
print(f"#define EXP_LN2LO_N {hexd(ln2lo)}")
print(f"#define EXP_INVLN2_N {hexd(d(N / log(2)))}")
R = log(2) / (2 * N) * mpf("1.02")
emit_consts("EXP_C", poly(lambda r: (expm1(r) - r) / r**2 if r != 0 else mpf(1) / 2, -R, R, 3, "exp: (e^r-1-r)/r^2"))

# expm1 on |x| <= ln2/2 directly: (e^x - 1 - x - x^2/2)/x^3
R = log(2) / 2 * mpf("1.01")
emit_consts("EXPM1_C", poly(lambda x: (expm1(x) - x - x**2 / 2) / x**3 if x != 0 else mpf(1) / 6, -R, R, 9, "expm1: (e^x-1-x-x^2/2)/x^3"))

# ---- log: table over z in [0x1.6p-1, 0x1.6p0) ----
OFF = 0x3fe6000000000000
LN = 128
ltab = []
for i in range(LN):
    lo = struct.unpack("<d", struct.pack("<Q", OFF + (i << 45)))[0]
    hi = struct.unpack("<d", struct.pack("<Q", OFF + ((i + 1) << 45)))[0]
    if lo <= 1.0 < hi:
        invc = 1.0
    else:
        invc = d(2 / (mpf(lo) + mpf(hi)))
    c = 1 / mpf(invc)
    chi, clo = dd(c)
    lhi, llo = dd(-log(mpf(invc)))
    ltab += [invc, chi, clo, lhi, llo]
print(f"#define LOG_N {LN}")
print(f"#define LOG_OFF 0x{OFF:x}ULL")
print("/* per entry: invc, c_hi, c_lo (c = 1/invc exactly), log(c) hi, lo */")
emit_array("log_tab", ltab, per=5)
l2hi, l2lo = split(log(2), 42)
print(f"#define LOG_LN2HI {hexd(l2hi)}")
print(f"#define LOG_LN2LO {hexd(l2lo)}")
R = mpf(2) ** -8 * mpf("1.02")
emit_consts("LOG_C", poly(lambda r: (log1p(r) - r + r**2 / 2) / r**3 if r != 0 else mpf(1) / 3, -R, R, 5, "log1p(r) tail on the table interval"))
R = mpf(1) / 16 * mpf("1.07")
emit_consts("LOG1_C", poly(lambda r: (log1p(r) - r + r**2 / 2 - r**3 / 3) / r**4 if r != 0 else -mpf(1) / 4, -R, R, 11, "log1p(r) tail after r^3/3, near 1"))
th, tl = dd(mpf(1) / 3)
print(f"#define THIRD_HI {hexd(th)}\n#define THIRD_LO {hexd(tl)}")
ih, il = dd(1 / log(2))
print(f"#define INVLN2_HI {hexd(ih)}\n#define INVLN2_LO {hexd(il)}")
ih, il = dd(1 / log(10))
print(f"#define INVLN10_HI {hexd(ih)}\n#define INVLN10_LO {hexd(il)}")

# ---- trig: pi/2 pieces, 2/pi bits, kernels ----
pio2 = pi / 2
p1, r1 = split(pio2, 33)
p2, r2 = split(pio2 - p1, 33)
p3, r3 = split(pio2 - p1 - p2, 33)
p3t = d(pio2 - p1 - p2 - p3)
for n, v in (("PIO2_1", p1), ("PIO2_2", p2), ("PIO2_3", p3), ("PIO2_3T", p3t)):
    print(f"#define {n} {hexd(v)}")
print(f"#define INVPIO2 {hexd(d(2 / pi))}")
# enough words for long double arguments (exponent up to 16383)
NW = 264
mp.prec = 64 * NW + 200
bits = int(mp.floor((2 / pi) * mpf(2) ** (64 * NW)))
mp.prec = 160
words = []
for k in range(NW):
    words.append(int(bits >> (64 * NW - 64 * (k + 1))) & (2**64 - 1))
print("/* 2/pi as 64-bit words, most significant first (bits after the binary point) */")
print(f"static const unsigned long long two_over_pi[{NW}] = {{")
for i in range(0, NW, 4):
    print("\t" + " ".join(f"0x{w:016x}ULL," for w in words[i:i + 4]))
print("};")
R = pi / 4 * mpf("1.01")
# The leading coefficients (-1/6, 1/24, 1/3) are applied exactly as
# double-doubles by the kernels; the fits cover what follows them.
emit_consts("SIN_C", poly(lambda z: (sin(sqrt(z)) - sqrt(z) + z * sqrt(z) / 6) / (z * z * sqrt(z)) if z != 0 else mpf(1) / 120, 0, R**2, 5, "sin: (sin x - x + x^3/6)/x^5 in z=x^2"))
emit_consts("COS_C", poly(lambda z: (cos(sqrt(z)) - 1 + z / 2 - z * z / 24) / z**3 if z != 0 else -mpf(1) / 720, 0, R**2, 5, "cos: (cos x - 1 + x^2/2 - x^4/24)/x^6 in z=x^2"))
for n, v in (("SIXTH", mpf(1) / 6), ("TWENTYFOURTH", mpf(1) / 24)):
    hi, lo = dd(v)
    print(f"#define {n}_HI {hexd(hi)}\n#define {n}_LO {hexd(lo)}")
T = mpf("0.6745")
emit_consts("TAN_C", poly(lambda z: (tan(sqrt(z)) - sqrt(z) - z * sqrt(z) / 3) / (z * z * sqrt(z)) if z != 0 else mpf(2) / 15, 0, T**2, 12, "tan: (tan x - x - x^3/3)/x^5 in z=x^2"))

# ---- inverse trig ----
for i, v in enumerate([mpf(1) / 2, mpf(1), mpf(3) / 2, None]):
    a = pi / 2 if v is None else atan(v)
    hi, lo = dd(a)
    print(f"#define ATAN_HI{i} {hexd(hi)}\n#define ATAN_LO{i} {hexd(lo)}")
R = mpf(7) / 16 * mpf("1.01")
emit_consts("ATAN_C", poly(lambda z: (atan(sqrt(z)) - sqrt(z) + z * sqrt(z) / 3) / (z * z * sqrt(z)) if z != 0 else mpf(1) / 5, 0, R**2, 12, "atan: (atan t - t + t^3/3)/t^5 in z=t^2"))
emit_consts("ASIN_C", poly(lambda z: (asin(sqrt(z)) - sqrt(z) - z * sqrt(z) / 6) / (z * z * sqrt(z)) if z != 0 else mpf(3) / 40, 0, mpf(1) / 4 * mpf("1.001"), 15, "asin: (asin s - s - s^3/6)/s^5 in z=s^2"))
hi, lo = dd(pi / 2)
print(f"#define PIO2_HI {hexd(hi)}\n#define PIO2_LO {hexd(lo)}")
hi, lo = dd(pi)
print(f"#define PI_HI {hexd(hi)}\n#define PI_LO {hexd(lo)}")
hi, lo = dd(pi / 4)
print(f"#define PIO4_HI {hexd(hi)}\n#define PIO4_LO {hexd(lo)}")

# ---- hyperbolic, small arguments ----
emit_consts("SINH_C", poly(lambda z: (sinh(sqrt(z)) - sqrt(z) - z * sqrt(z) / 6) / (z * z * sqrt(z)) if z != 0 else mpf(1) / 120, 0, mpf("0.2525"), 5, "sinh: (sinh x - x - x^3/6)/x^5 in z=x^2"))
emit_consts("TANH_C", poly(lambda z: (tanh(sqrt(z)) - sqrt(z) + z * sqrt(z) / 3) / (z * z * sqrt(z)) if z != 0 else mpf(2) / 15, 0, mpf("0.3056"), 12, "tanh: (tanh x - x + x^3/3)/x^5 in z=x^2"))
emit_consts("ASINH_C", poly(lambda z: (asinh(sqrt(z)) - sqrt(z) + z * sqrt(z) / 6) / (z * z * sqrt(z)) if z != 0 else mpf(3) / 40, 0, mpf("0.2525"), 16, "asinh: (asinh x - x + x^3/6)/x^5 in z=x^2"))

# ---- erf, erfc ----
from mpmath import erf as mp_erf, erfc as mp_erfc, loggamma, gamma as mp_gamma, euler, psi
mp.prec = 200
C = 2 / sqrt(pi)
hi, lo = dd(C)
print(f"#define ERF_C_HI {hexd(hi)}\n#define ERF_C_LO {hexd(lo)}")
P0 = -C / 3
hi, lo = dd(P0)
print(f"#define ERF_P0_HI {hexd(hi)}\n#define ERF_P0_LO {hexd(lo)}")
P1 = C / 10
hi, lo = dd(P1)
print(f"#define ERF_P1_HI {hexd(hi)}\n#define ERF_P1_LO {hexd(lo)}")
emit_consts("ERF_R", poly(lambda z: (mp_erf(sqrt(z)) / sqrt(z) - C - P0 * z - P1 * z * z) / z**3 if z != 0 else -C / 42, 0, 1, 10, "erf: (erf(x)/x - C - P0 z - P1 z^2)/z^3, z = x^2"))
# erfc(x) = e^(-x^2) w(x); on each interval w = W0 + W1 t + t^2 R(t), t = x - c
w = lambda x: exp(x * x) * mp_erfc(x)
edges = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.75, 5.5, 6.5, 7.75, 9.25, 11, 13.5, 16.5, 20.5, 27.5]
degs = [12, 12, 11, 11, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 15]
print(f"#define ERFC_NINT {len(degs)}")
print("static const double erfc_edges[] = {" + ", ".join(hexd(e) for e in edges) + "};")
rows = []
maxdeg = max(degs)
for (a, b), deg in zip(zip(edges, edges[1:]), degs):
    c = (mpf(a) + mpf(b)) / 2
    h = (mpf(b) - mpf(a)) / 2
    W0 = w(c)
    W1 = 2 * c * W0 - C
    W2 = (2 * W0 + 2 * c * W1) / 2
    f = lambda t: (w(c + t) - W0 - W1 * t) / t**2 if t != 0 else W2
    cc, err = remez(f, -h, h, deg)
    print(f"/* erfc [{a}, {b}]: degree {deg}, relative error {float(err * h * h / w(mpf(b))):.3g} */")
    w0h, w0l = dd(W0)
    w1h, w1l = dd(W1)
    coefs = [d(v) for v in cc] + [0.0] * (maxdeg - deg)
    rows.append([d(c), w0h, w0l, w1h, w1l, float(deg)] + coefs)
print(f"#define ERFC_ROW {6 + maxdeg + 1}")
print("/* per interval: centre, W0 hi, lo, W1 hi, lo, degree, R coefficients */")
print(f"static const double erfc_tab[{len(rows)} * {6 + maxdeg + 1}] = {{")
for r in rows:
    print("\t" + ", ".join(hexd(v) for v in r) + ",")
print("};")

# ---- lgamma, tgamma ----
C0 = 1 - euler
hi, lo = dd(C0)
print(f"#define LGAM_C0_HI {hexd(hi)}\n#define LGAM_C0_LO {hexd(lo)}")
lgq, err = remez(lambda t: (loggamma(2 + t) / t - C0) / t if t != 0 else psi(1, 2) / 2, mpf(-0.5), mpf(0.5), 20)
print(f"/* lgamma(2+t) = t (C0 + t Q(t)): degree 20 on [-0.5, 0.5], max abs error {float(err):.3g} */")
emit_consts("LGAM_Q", [d(v) for v in lgq])
for k in (0, 1):  # these two are applied as double-doubles
    print(f"#define LGAM_Q{k}_LO {hexd(d(lgq[k] - mpf(d(lgq[k]))))}")
G0 = mp_gamma(mpf(2.5))
G1 = G0 * psi(0, mpf(2.5))
for n, v in (("TGAM_G0", G0), ("TGAM_G1", G1)):
    hi, lo = dd(v)
    print(f"#define {n}_HI {hexd(hi)}\n#define {n}_LO {hexd(lo)}")
emit_consts("TGAM_R", poly(lambda t: (mp_gamma(mpf(2.5) + t) - G0 - G1 * t) / t**2 if t != 0 else G0 * (psi(0, mpf(2.5))**2 + psi(1, mpf(2.5))) / 2, -0.5, 0.5, 18, "gamma(2.5+t) = G0 + G1 t + t^2 R(t)"))
def stirT(v):
    if v == 0:
        return mpf(1) / 12
    x = 1 / sqrt(v)
    return (loggamma(x) - ((x - mpf(1) / 2) * log(x) - x + log(2 * pi) / 2)) * x
emit_consts("STIR_T", poly(stirT, 0, mpf(1) / 144, 5, "Stirling: lgamma(x) - ((x-1/2)log x - x + log(2pi)/2) = T(1/x^2)/x, x >= 12"))
for n, v in (("HLOG2PI", log(2 * pi) / 2), ("LOGPI", log(pi))):
    hi, lo = dd(v)
    print(f"#define {n}_HI {hexd(hi)}\n#define {n}_LO {hexd(lo)}")

# ==== long double (x87 extended, 64-bit significand) ====
def hexl(v):
    """mpf -> long double hex literal (round to nearest, 64 bits)."""
    v = mpf(v)
    if v == 0:
        return "0.0L"
    s = "-" if v < 0 else ""
    v = abs(v)
    e = int(mp.floor(mp.log(v, 2)))
    M = int(mp.nint(v * mpf(2) ** (63 - e)))
    if M >= 2**64:
        M //= 2
        e += 1
    if M < 2**63:
        M *= 2
        e -= 1
    return f"{s}0x{M:016x}p{e - 63}L"

def ldv(v):
    """value of the long double nearest v"""
    v = mpf(v)
    if v == 0:
        return mpf(0)
    e = int(mp.floor(mp.log(abs(v), 2)))
    return mp.nint(v * mpf(2) ** (63 - e)) * mpf(2) ** (e - 63)

def ddl(v):
    hi = ldv(v)
    return hi, ldv(mpf(v) - hi)

def splitl(x, bits):
    x = mpf(x)
    e = int(mp.floor(mp.log(abs(x), 2)))
    q = mpf(2) ** (e - bits + 1)
    hi = mp.nint(x / q) * q
    return hi, ldv(x - hi)

def polyl(f, a, b, deg, name):
    c, err = remez(f, a, b, deg)
    print(f"/* {name}: degree {deg} on [{float(a):.6g}, {float(b):.6g}], max abs error {float(err):.3g} */")
    return [ldv(v) for v in c]

def emit_l(prefix, vals):
    for i, v in enumerate(vals):
        print(f"#define {prefix}{i} {hexl(v)}")

mp.prec = 256
print("/* ---- long double ---- */")
print("#define LEXP_N 128")
print("static const long double lexp_tab[256] = {")
for j in range(128):
    hi, lo = ddl(mpf(2) ** (mpf(j) / 128))
    print(f"\t{hexl(hi)}, {hexl(lo)},")
print("};")
hi, lo = splitl(log(2) / 128, 43)
print(f"#define LEXP_LN2HI_N {hexl(hi)}\n#define LEXP_LN2LO_N {hexl(lo)}")
print(f"#define LEXP_INVLN2_N {hexl(128 / log(2))}")
R = log(2) / 256 * mpf("1.02")
emit_l("LEXP_C", polyl(lambda r: (exp(r) - 1 - r - r * r / 2) / r**3 if r != 0 else mpf(1) / 6, -R, R, 4, "long exp: (e^r-1-r-r^2/2)/r^3"))
R = mpf("0.3466") * mpf("1.01")
emit_l("LEXPM1_C", polyl(lambda r: (expm1(r) - r - r * r / 2) / r**3 if r != 0 else mpf(1) / 6, -R, R, 13, "long expm1: (e^x-1-x-x^2/2)/x^3"))
print("/* log: c = 1 + i/128 for i in [-32, 64]; per entry invc (53 bits), -log(invc) hi, lo */")
print("#define LLOG_I0 32")
print("static const long double llog_tab[97 * 3] = {")
for i in range(-32, 65):
    invc = mpf(d(1 / (1 + mpf(i) / 128)))
    hi, lo = ddl(-log(invc))
    print(f"\t{hexl(invc)}, {hexl(hi)}, {hexl(lo)},")
print("};")
R = mpf("0.0053")
emit_l("LLOG_C", polyl(lambda r: (log1p(r) - r + r * r / 2) / r**3 if r != 0 else mpf(1) / 3, -R, R, 7, "long log1p tail: (log1p(r)-r+r^2/2)/r^3"))
hi, lo = splitl(log(2), 48)
print(f"#define LLN2_HI {hexl(hi)}\n#define LLN2_LO {hexl(lo)}")
for n, v in (("LINVLN2", 1 / log(2)), ("LINVLN10", 1 / log(10)), ("LLN2", log(2))):
    hi, lo = ddl(v)
    print(f"#define {n}_H {hexl(hi)}\n#define {n}_L {hexl(lo)}")
pio2 = pi / 2
p1, r1 = splitl(pio2, 32)
p2, r2 = splitl(pio2 - p1, 32)
p3, r3 = splitl(pio2 - p1 - p2, 32)
p3t = ldv(pio2 - p1 - p2 - p3)
for n, v in (("LPIO2_1", p1), ("LPIO2_2", p2), ("LPIO2_3", p3), ("LPIO2_3T", p3t)):
    print(f"#define {n} {hexl(v)}")
print(f"#define LINVPIO2 {hexl(2 / pi)}")
for n, v in (("LPIO2", pi / 2), ("LPI", pi), ("LPIO4", pi / 4)):
    hi, lo = ddl(v)
    print(f"#define {n}_H {hexl(hi)}\n#define {n}_L {hexl(lo)}")

# ---- long double erf, erfc ----
mp.prec = 256
hi, lo = ddl(C)
print(f"#define LERF_C_H {hexl(hi)}\n#define LERF_C_L {hexl(lo)}")
hi, lo = ddl(P0)
print(f"#define LERF_P0_H {hexl(hi)}\n#define LERF_P0_L {hexl(lo)}")
hi, lo = ddl(P1)
print(f"#define LERF_P1_H {hexl(hi)}\n#define LERF_P1_L {hexl(lo)}")
emit_l("LERF_R", polyl(lambda z: (mp_erf(sqrt(z)) / sqrt(z) - C - P0 * z - P1 * z * z) / z**3 if z != 0 else -C / 42, 0, 1, 13, "long erf: (erf(x)/x - C - P0 z - P1 z^2)/z^3"))
ldegs = [15, 15, 14, 14, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 18]
lmax = max(ldegs)
lrows = []
for (a, b), deg in zip(zip(edges, edges[1:]), ldegs):
    c = (mpf(a) + mpf(b)) / 2
    h = (mpf(b) - mpf(a)) / 2
    W0 = w(c)
    W1 = 2 * c * W0 - C
    W2 = (2 * W0 + 2 * c * W1) / 2
    f = lambda t: (w(c + t) - W0 - W1 * t) / t**2 if t != 0 else W2
    cc, err = remez(f, -h, h, deg)
    print(f"/* long erfc [{a}, {b}]: degree {deg}, relative error {float(err * h * h / w(mpf(b))):.3g} */")
    w0h, w0l = ddl(W0)
    w1h, w1l = ddl(W1)
    coefs = [ldv(v) for v in cc] + [mpf(0)] * (lmax - deg)
    lrows.append([ldv(c), w0h, w0l, w1h, w1l, mpf(deg)] + coefs)
print(f"#define LERFC_ROW {6 + lmax + 1}")
print(f"static const long double lerfc_tab[{len(lrows)} * {6 + lmax + 1}] = {{")
for r in lrows:
    print("\t" + ", ".join(hexl(v) for v in r) + ",")
print("};")

# ---- long double lgamma, tgamma ----
hi, lo = ddl(C0)
print(f"#define LLGAM_C0_H {hexl(hi)}\n#define LLGAM_C0_L {hexl(lo)}")
llgq, err = remez(lambda t: (loggamma(2 + t) / t - C0) / t if t != 0 else psi(1, 2) / 2, mpf(-0.5), mpf(0.5), 24)
print(f"/* long lgamma(2+t) = t (C0 + t Q(t)): degree 24 on [-0.5, 0.5], max abs error {float(err):.3g} */")
emit_l("LLGAM_Q", [ldv(v) for v in llgq])
for k in (0, 1):
    print(f"#define LLGAM_Q{k}_L {hexl(ldv(llgq[k] - ldv(llgq[k])))}")
for n, v in (("LTGAM_G0", G0), ("LTGAM_G1", G1)):
    hi, lo = ddl(v)
    print(f"#define {n}_H {hexl(hi)}\n#define {n}_L {hexl(lo)}")
emit_l("LTGAM_R", polyl(lambda t: (mp_gamma(mpf(2.5) + t) - G0 - G1 * t) / t**2 if t != 0 else G0 * (psi(0, mpf(2.5))**2 + psi(1, mpf(2.5))) / 2, -0.5, 0.5, 22, "long gamma(2.5+t) = G0 + G1 t + t^2 R(t)"))
emit_l("LSTIR_T", polyl(stirT, 0, mpf(1) / 256, 6, "long Stirling, x >= 16: T(1/x^2)/x"))
for n, v in (("LHLOG2PI", log(2 * pi) / 2), ("LLOGPI", log(pi)), ("LPI2", pi)):
    hi, lo = ddl(v)
    print(f"#define {n}_H {hexl(hi)}\n#define {n}_L {hexl(lo)}")
