#!/usr/bin/perl
# Generate src/unicode_tables.h from Perl's Unicode database.
#
#     perl scripts/gen-unicode.pl > src/unicode_tables.h
#
# The classes follow glibc's C.UTF-8 definitions (localedata/unicode-gen),
# so behaviour matches glibc built on the same Unicode version:
#   alpha  Alphabetic, plus non-ASCII decimal digits
#   upper  has a lowercase mapping, or Uppercase
#   lower  has an uppercase mapping, or Lowercase (and U+00DF)
#   graph  assigned, not a control, not a space character
#   print  assigned, not a control, not a line/paragraph separator
#   punct  graph and not alpha and not an ASCII digit
#   space  ASCII white space and Z* separators except no-break spaces
#   width  -1: unassigned, surrogates, controls, line/paragraph separators;
#          0: Mn, Me, Cf (but not U+00AD or prepended concatenation marks),
#             Hangul medial/final jamo, U+200B; 2: East Asian Wide/Fullwidth.
use strict;
use warnings;
use Unicode::UCD qw(prop_invlist prop_invmap);

my $MAX = 0x110000;

sub set_of { my %s; my @l = prop_invlist($_[0]); for (my $i = 0; $i < @l; $i += 2) { my $e = $i + 1 < @l ? $l[$i + 1] : $MAX; $s{$_} = 1 for $l[$i] .. $e - 1; } return \%s; }

my ($gc_r, $gc_m, $gc_f, $gc_d) = prop_invmap('General_Category');
my @gc = ('Cn') x $MAX;
for my $i (0 .. $#$gc_r) { my $e = $i < $#$gc_r ? $gc_r->[$i + 1] : $MAX; $gc[$_] = $gc_m->[$i] for $gc_r->[$i] .. $e - 1; }

sub simple_map {
	my ($r, $m, $f, $d) = prop_invmap($_[0]);
	my %map;
	for my $i (0 .. $#$r) {
		my $v = $m->[$i];
		next if !defined $v || ref $v || $v eq '0' && $f eq 'a';
		my $e = $i < $#$r ? $r->[$i + 1] : $MAX;
		for my $c ($r->[$i] .. $e - 1) {
			my $t = $f eq 'a' ? $v + ($c - $r->[$i]) : $v;
			$map{$c} = $t if $t != $c;
		}
	}
	return \%map;
}

my $alphabetic = set_of('Alphabetic');
my $uppercase = set_of('Uppercase');
my $lowercase = set_of('Lowercase');
my $pcm = set_of('Prepended_Concatenation_Mark');
my $wide = set_of('East_Asian_Width=Wide');
my $full = set_of('East_Asian_Width=Fullwidth');
my $tolower = simple_map('Simple_Lowercase_Mapping');
my $toupper = simple_map('Simple_Uppercase_Mapping');

my %nbsp = (0xa0 => 1, 0x2007 => 1, 0x202f => 1);
sub is_cntrl { my $c = shift; $gc[$c] eq 'Cc' || $gc[$c] eq 'Zl' || $gc[$c] eq 'Zp' }
sub is_space { my $c = shift; ($c == 0x20 || ($c >= 9 && $c <= 13)) || ($gc[$c] =~ /^Z/ && !$nbsp{$c}) }
sub is_alpha { my $c = shift; $alphabetic->{$c} || ($gc[$c] eq 'Nd' && !($c >= 0x30 && $c <= 0x39)) }
sub is_upper { my $c = shift; exists $tolower->{$c} || $uppercase->{$c} }
sub is_lower { my $c = shift; exists $toupper->{$c} || $lowercase->{$c} || $c == 0xdf }
sub assigned { my $c = shift; $gc[$c] ne 'Cn' && $gc[$c] ne 'Cs' }
sub is_graph { my $c = shift; assigned($c) && $gc[$c] ne 'Cc' && !is_space($c) }
sub is_print { my $c = shift; assigned($c) && $gc[$c] ne 'Cc' && $gc[$c] ne 'Zl' && $gc[$c] ne 'Zp' }
sub is_punct { my $c = shift; is_graph($c) && !is_alpha($c) && !($c >= 0x30 && $c <= 0x39) }
sub width {
	my $c = shift;
	return 0 if $c == 0;
	return -1 if !assigned($c) || $gc[$c] eq 'Cc' || $gc[$c] eq 'Zl' || $gc[$c] eq 'Zp';
	return 1 if $c == 0xad || $pcm->{$c};
	return 0 if $gc[$c] =~ /^(Mn|Me|Cf)$/ || ($c >= 0x1160 && $c <= 0x11ff) || ($c >= 0xd7b0 && $c <= 0xd7ff) || $c == 0x200b;
	return 2 if $wide->{$c} || $full->{$c};
	return 1;
}

sub ranges {
	my $p = shift;
	my (@out, $start);
	for my $c (0 .. $MAX - 1) {
		if ($p->($c)) { $start //= $c; }
		elsif (defined $start) { push @out, [$start, $c - 1]; undef $start; }
	}
	push @out, [$start, $MAX - 1] if defined $start;
	return @out;
}

sub emit_ranges {
	my ($name, @r) = @_;
	print "static const uint32_t ${name}[][2] = {\n";
	while (my @chunk = splice(@r, 0, 4)) {
		print "\t", join(" ", map { sprintf "{0x%x, 0x%x},", @$_ } @chunk), "\n";
	}
	print "};\n";
}

sub emit_case {
	my ($name, $map) = @_;
	my @runs;
	for my $c (sort { $a <=> $b } keys %$map) {
		my $d = $map->{$c} - $c;
		if (@runs) {
			my $r = $runs[-1];
			my $gap = $c - $r->[1];
			if ($r->[2] == $d && ($r->[3] ? $gap == $r->[3] : ($gap == 1 || $gap == 2))) {
				$r->[3] ||= $gap;
				$r->[1] = $c;
				next;
			}
		}
		push @runs, [$c, $c, $d, 0];
	}
	print "static const struct { uint32_t start, end; int32_t delta; uint8_t step; } ${name}[] = {\n";
	printf "\t{0x%x, 0x%x, %d, %d},\n", $_->[0], $_->[1], $_->[2], $_->[3] || 1 for @runs;
	print "};\n";
}

print "/* Generated by scripts/gen-unicode.pl from Unicode ", Unicode::UCD::UnicodeVersion(), " - do not edit. */\n";
emit_ranges('u_alpha', ranges(\&is_alpha));
emit_ranges('u_upper', ranges(\&is_upper));
emit_ranges('u_lower', ranges(\&is_lower));
emit_ranges('u_punct', ranges(\&is_punct));
emit_ranges('u_cntrl', ranges(\&is_cntrl));
emit_ranges('u_graph', ranges(\&is_graph));
emit_ranges('u_print', ranges(\&is_print));
emit_ranges('u_space', ranges(\&is_space));
emit_ranges('u_blank', ranges(sub { my $c = shift; $c == 9 || ($gc[$c] eq 'Zs' && !$nbsp{$c}) }));
emit_ranges('u_width0', ranges(sub { width($_[0]) == 0 }));
emit_ranges('u_width2', ranges(sub { width($_[0]) == 2 }));
emit_ranges('u_nonprint', ranges(sub { width($_[0]) < 0 }));
emit_case('u_tolower', $tolower);
emit_case('u_toupper', $toupper);
