#!/usr/bin/env python3
"""Generate src/math/tables.h: lookup tables and polynomial coefficients
for the double-precision math functions, computed with mpmath at 256 bits.

    python3 scripts/gen-math.py > src/math/tables.h

Needs mpmath (pip install mpmath); only for regenerating the header."""
import struct
from mpmath import mp, mpf, exp, log, log1p, expm1, pi, sin, cos, tan, atan, asin, sqrt, floor, ldexp

mp.prec = 160

def d(x):
    """Round an mpf to the nearest double."""
    return float(mp.mpf(x))

def hexd(x):
    return float(x).hex()

def split(x, bits):
    """x as hi (with at most `bits` significant bits) + lo."""
    x = mpf(x)
    if x == 0:
        return 0.0, 0.0
    e = int(mp.floor(mp.log(abs(x), 2)))
    q = mpf(2) ** (e - bits + 1)
    hi = mp.nint(x / q) * q
    return float(hi), d(x - hi)

def dd(x):
    hi = d(x)
    return hi, d(mpf(x) - hi)

def peval(c, x):
    r = mpf(0)
    for v in reversed(c):
        r = r * x + v
    return r

def remez(f, a, b, deg, iters=30):
    """Minimax polynomial (absolute error) by the Remez exchange."""
    a, b = mpf(a), mpf(b)
    n = deg + 2
    # initial reference: Chebyshev extrema
    snap = lambda x: mpf(0) if abs(x) < mpf(2) ** -60 else x
    ref = [snap((a + b) / 2 - (b - a) / 2 * mp.cos(pi * k / (n - 1))) for k in range(n)]
    c = None
    for _ in range(iters):
        A = mp.matrix(n, n)
        y = mp.matrix(n, 1)
        for i, x in enumerate(ref):
            for j in range(deg + 1):
                A[i, j] = x ** j
            A[i, deg + 1] = (-1) ** i
            y[i] = f(x)
        sol = mp.lu_solve(A, y)
        c = [sol[j] for j in range(deg + 1)]
        err = lambda x: f(x) - peval(c, x)
        # locate the extrema of the error between sign changes
        grid = [snap(a + (b - a) * k / 2000) for k in range(2001)]
        vals = [err(x) for x in grid]
        ext = []
        start = 0
        for k in range(1, len(grid) + 1):
            if k == len(grid) or (vals[k] > 0) != (vals[start] > 0):
                seg = range(start, k)
                m = max(seg, key=lambda t: abs(vals[t]))
                ext.append(grid[m])
                start = k
        if len(ext) < n:
            break
        # keep n alternating extrema with the largest errors
        while len(ext) > n:
            if abs(err(ext[0])) < abs(err(ext[-1])):
                ext.pop(0)
            else:
                ext.pop()
        ref = ext
    grid = [snap(a + (b - a) * k / 20000) for k in range(20001)]
    maxerr = max(abs(f(x) - peval(c, x)) for x in grid)
    return c, maxerr

def poly(f, a, b, deg, name):
    """Minimax fit; coefficients lowest degree first."""
    c, err = remez(f, a, b, deg)
    print(f"/* {name}: degree {deg} on [{float(a):.6g}, {float(b):.6g}], max abs error {float(err):.3g} */")
    return [d(v) for v in c]

def emit_array(name, vals, per=2):
    print(f"static const double {name}[{len(vals)}] = {{")
    for i in range(0, len(vals), per):
        print("\t" + " ".join(f"{hexd(v)}," for v in vals[i:i + per]))
    print("};")

def emit_consts(prefix, vals):
    for i, v in enumerate(vals):
        print(f"#define {prefix}{i} {hexd(v)}")

print("/* Generated by scripts/gen-math.py - do not edit. */")

# ---- exp / exp2 / expm1: 2^(j/N) table ----
N = 128
tab = []
for j in range(N):
    hi, lo = dd(mpf(2) ** (mpf(j) / N))
    tab += [hi, lo]
print(f"#define EXP_N {N}")
emit_array("exp_tab", tab)
ln2hi, ln2lo = split(log(2) / N, 35)
print(f"#define EXP_LN2HI_N {hexd(ln2hi)}")
print(f"#define EXP_LN2LO_N {hexd(ln2lo)}")
print(f"#define EXP_INVLN2_N {hexd(d(N / log(2)))}")
R = log(2) / (2 * N) * mpf("1.02")
emit_consts("EXP_C", poly(lambda r: (expm1(r) - r) / r**2 if r != 0 else mpf(1) / 2, -R, R, 3, "exp: (e^r-1-r)/r^2"))

# expm1 on |x| <= ln2/2 directly: (e^x - 1 - x - x^2/2)/x^3
R = log(2) / 2 * mpf("1.01")
emit_consts("EXPM1_C", poly(lambda x: (expm1(x) - x - x**2 / 2) / x**3 if x != 0 else mpf(1) / 6, -R, R, 9, "expm1: (e^x-1-x-x^2/2)/x^3"))

# ---- log: table over z in [0x1.6p-1, 0x1.6p0) ----
OFF = 0x3fe6000000000000
LN = 128
ltab = []
for i in range(LN):
    lo = struct.unpack("<d", struct.pack("<Q", OFF + (i << 45)))[0]
    hi = struct.unpack("<d", struct.pack("<Q", OFF + ((i + 1) << 45)))[0]
    if lo <= 1.0 < hi:
        invc = 1.0
    else:
        invc = d(2 / (mpf(lo) + mpf(hi)))
    c = 1 / mpf(invc)
    chi, clo = dd(c)
    lhi, llo = dd(-log(mpf(invc)))
    ltab += [invc, chi, clo, lhi, llo]
print(f"#define LOG_N {LN}")
print(f"#define LOG_OFF 0x{OFF:x}ULL")
print("/* per entry: invc, c_hi, c_lo (c = 1/invc exactly), log(c) hi, lo */")
emit_array("log_tab", ltab, per=5)
l2hi, l2lo = split(log(2), 42)
print(f"#define LOG_LN2HI {hexd(l2hi)}")
print(f"#define LOG_LN2LO {hexd(l2lo)}")
R = mpf(2) ** -8 * mpf("1.02")
emit_consts("LOG_C", poly(lambda r: (log1p(r) - r + r**2 / 2) / r**3 if r != 0 else mpf(1) / 3, -R, R, 5, "log1p(r) tail on the table interval"))
R = mpf(1) / 16 * mpf("1.07")
emit_consts("LOG1_C", poly(lambda r: (log1p(r) - r + r**2 / 2 - r**3 / 3) / r**4 if r != 0 else -mpf(1) / 4, -R, R, 11, "log1p(r) tail after r^3/3, near 1"))
th, tl = dd(mpf(1) / 3)
print(f"#define THIRD_HI {hexd(th)}\n#define THIRD_LO {hexd(tl)}")
ih, il = dd(1 / log(2))
print(f"#define INVLN2_HI {hexd(ih)}\n#define INVLN2_LO {hexd(il)}")
ih, il = dd(1 / log(10))
print(f"#define INVLN10_HI {hexd(ih)}\n#define INVLN10_LO {hexd(il)}")

# ---- trig: pi/2 pieces, 2/pi bits, kernels ----
pio2 = pi / 2
p1, r1 = split(pio2, 33)
p2, r2 = split(pio2 - p1, 33)
p3, r3 = split(pio2 - p1 - p2, 33)
p3t = d(pio2 - p1 - p2 - p3)
for n, v in (("PIO2_1", p1), ("PIO2_2", p2), ("PIO2_3", p3), ("PIO2_3T", p3t)):
    print(f"#define {n} {hexd(v)}")
print(f"#define INVPIO2 {hexd(d(2 / pi))}")
mp.prec = 1400
bits = int(mp.floor((2 / pi) * mpf(2) ** 1280))
mp.prec = 160
words = []
for k in range(20):
    words.append(int(bits >> (1280 - 64 * (k + 1))) & (2**64 - 1))
print("/* 2/pi as 64-bit words, most significant first (bits after the binary point) */")
print("static const unsigned long long two_over_pi[20] = {")
for i in range(0, 20, 4):
    print("\t" + " ".join(f"0x{w:016x}ULL," for w in words[i:i + 4]))
print("};")
R = pi / 4 * mpf("1.01")
# The leading coefficients (-1/6, 1/24, 1/3) are applied exactly as
# double-doubles by the kernels; the fits cover what follows them.
emit_consts("SIN_C", poly(lambda z: (sin(sqrt(z)) - sqrt(z) + z * sqrt(z) / 6) / (z * z * sqrt(z)) if z != 0 else mpf(1) / 120, 0, R**2, 5, "sin: (sin x - x + x^3/6)/x^5 in z=x^2"))
emit_consts("COS_C", poly(lambda z: (cos(sqrt(z)) - 1 + z / 2 - z * z / 24) / z**3 if z != 0 else -mpf(1) / 720, 0, R**2, 5, "cos: (cos x - 1 + x^2/2 - x^4/24)/x^6 in z=x^2"))
for n, v in (("SIXTH", mpf(1) / 6), ("TWENTYFOURTH", mpf(1) / 24)):
    hi, lo = dd(v)
    print(f"#define {n}_HI {hexd(hi)}\n#define {n}_LO {hexd(lo)}")
T = mpf("0.6745")
emit_consts("TAN_C", poly(lambda z: (tan(sqrt(z)) - sqrt(z) - z * sqrt(z) / 3) / (z * z * sqrt(z)) if z != 0 else mpf(2) / 15, 0, T**2, 12, "tan: (tan x - x - x^3/3)/x^5 in z=x^2"))

# ---- inverse trig ----
for i, v in enumerate([mpf(1) / 2, mpf(1), mpf(3) / 2, None]):
    a = pi / 2 if v is None else atan(v)
    hi, lo = dd(a)
    print(f"#define ATAN_HI{i} {hexd(hi)}\n#define ATAN_LO{i} {hexd(lo)}")
R = mpf(7) / 16 * mpf("1.01")
emit_consts("ATAN_C", poly(lambda z: (atan(sqrt(z)) - sqrt(z) + z * sqrt(z) / 3) / (z * z * sqrt(z)) if z != 0 else mpf(1) / 5, 0, R**2, 12, "atan: (atan t - t + t^3/3)/t^5 in z=t^2"))
emit_consts("ASIN_C", poly(lambda z: (asin(sqrt(z)) - sqrt(z) - z * sqrt(z) / 6) / (z * z * sqrt(z)) if z != 0 else mpf(3) / 40, 0, mpf(1) / 4 * mpf("1.001"), 15, "asin: (asin s - s - s^3/6)/s^5 in z=s^2"))
hi, lo = dd(pi / 2)
print(f"#define PIO2_HI {hexd(hi)}\n#define PIO2_LO {hexd(lo)}")
hi, lo = dd(pi)
print(f"#define PI_HI {hexd(hi)}\n#define PI_LO {hexd(lo)}")
hi, lo = dd(pi / 4)
print(f"#define PIO4_HI {hexd(hi)}\n#define PIO4_LO {hexd(lo)}")
